### ISSUE TITLE
Recommend to reformat table for readability

### ISSUE THREAD

**Issue by thecolorblocks** [jokie88/ordinalpublicgoods#5]
I recommend to change the inscription ID column to link format, like so:

[inscription](https://ordinals.com/preview/6fb976ab49dcec017f1e201e84395983204ae1a7c2abf7ced0a85d692e442799i0)

So that the table won't be too wide to read.

Shall I create a pull request?

**Comment by jokie88** [comment]
great idea it is a bit large… yes a PR would be wonderful!

**Comment by thecolorblocks** [comment]
Created PR here: https://github.com/jokie88/ordinalpublicgoods/pull/7

**Comment by jokie88** [comment]
thank you!!!
